name: Delete dev- branches after PR merge

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: '消去するブランチの名前を入力'
        required: true

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    steps:
      - name: Delete dev- prefixed branch
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const eventName = context.eventName;
            const payload = context.payload;
            // ブランチ名を設定
            let branchName = '';
            if (eventName === 'workflow_dispatch') {
              branchName = payload.inputs.branch;
            } else if (eventName === 'pull_request' ) {
              branchName = 'dev-' + payload.pull_request.head.ref;
            }
            // 用心のためブランチ名が与えられているかを確認。
            if (!branchName) {
              console.log('Branch name is not provided. Skipping deletion.');
              return;
            }
            // 消すブランチをログに記載。
            console.log(`Deleting branch: ${branchName}`);
            
            try {
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: `heads/${branchName}`,
              });
            } catch (error) {
              // 失敗時はエラーメッセージを出力
              console.log(`Error deleting branch: ${error.message}`);
            }
