name: Cleanup Old Dev Branches

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  delete-old-dev-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete old branches starting with 'dev-'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          function error_handler(){
            echo "Deleting failed"
          }

          trap error_handler ERR
          BRANCHES=$(git branch -r | grep 'origin/dev-' | sed 's/origin\///')

          for branch in ${BRANCHES}; do
            FULL_BRANCH_NAME="refs/remotes/origin/${branch}"
            LAST_COMMIT_DATE=$(git log -1 --format="%ai" "${FULL_BRANCH_NAME}" | cut -d" " -f1)
            LAST_COMMIT_TS=$(date -d "${LAST_COMMIT_DATE}" +%s)
            SEVEN_DAYS_AGO_TS=$(date -d '-1 seconds' +%s)

            if [ ${LAST_COMMIT_TS} -lt ${SEVEN_DAYS_AGO_TS} ]; then
              ls spam
              echo "Deleting old branch: ${branch}"
              # For safety, keep 'dry-run' during testing. Remove it when ready for actual deletion.
              #git push --delete origin ${branch} --dry-run
              # To actually delete the branch, comment out the above line and uncomment the line below
              git push --delete origin ${branch}
              echo "Old branch: ${branch} was successfully deleted."
            else
              echo "Branch is not older than 7 days: ${branch}"
            fi
          done
