name: Delete dev- branches

on:
  schedule:
    # At 04:00 on every Monday in Japan (UTC+9)
    - cron: '0 19 * * 0'
  workflow_dispatch:

jobs:
  delete_dev_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete dev- branches
        run: |
          git fetch --all
          git branch -r | grep 'origin/dev-' | sed 's/origin\///' | xargs -I {} git push origin --delete {}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}